print("the following questions are going to be realated to a story that will apear before you... ")
print("please go ahead and fill in the question with what they ask or what you perfer to awnser with... ")
print('as a reminder please do not put in anything bad for your safty.')
name1 = input('enter your name')
place1 = input('enter a place')
animal1 = input('name an animal')
person1 = input("name a friend")
pet1 = input("what is your pet")
friends1 = input("how many friends do you have? ")
print("so your name is "+name1+" you live at your "+place1+" your favorit animal is a "+animal1+"...")
print("your friend is "+person1+" your pet is a "+pet1+" and you have "+friends1+" friends? ")
print("did i get all that correct "+name1+"?")
print('it is most likly that most of these things are not correct at all...')
print("but never the less you did awnser the questions")
print("                                                                             ")
print("now then please awnser these last 3 questions with full honesty...")
sit1 = input("are you currently sitting?")
doing1 = input("are you sleepy")
real1 = input("is your name mr.scott?ฅ^•ﻌ•^ฅ")
print("thank you for your co-operation.")
print("end testing")
{} .format(pet1)